version: '3.9'

services:

  sitefinitysql:
    hostname: sitefinitysql
    environment:
      - SA_PASSWORD=Sitefinity14@2022
      - ACCEPT_EULA=Y      
      - MSSQL_PID=Express
    volumes:
      - ./data/sql_data/data:/var/opt/mssql/data
      - ./data/sql_data/backup:/var/opt/mssql/backup

  sitefinitywebapp:
    hostname: cms.sitefinity.local
    volumes:
      - ./data/app_data:C:/inetpub/wwwroot/App_Data 

  sitefinityrenderer:
    image: sitefinityrenderer:dev
    hostname: www.sitefinity.local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
    ports:
      - "5000:5000"
      - "5001:5001" 


  elasticsetup:
   volumes:
      - ./data/certs:/usr/share/elasticsearch/config/certs
      
  es01:
    hostname:  elastic.sitefinity.local
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./data/certs:/usr/share/elasticsearch/config/certs
  
 
 
   
      