version: '2.5'

services:
  sitefinitysql:
    hostname: sitefinitysql
    container_name: sitefinitysql
    environment:
      - SA_PASSWORD=Sitefinity14@2022
      - ACCEPT_EULA=Y      
      - MSSQL_PID=Express
    ports:
      - "5433:1433"
    volumes:
        - ./data/sql_data/data:/var/opt/mssql/data
        - ./data/sql_data/backup:/var/opt/mssql/backup
  aapmsitefinitywebapp:
    ports:
      - "8085:80"
    volumes:
      - ./data/app_data:C:/inetpub/wwwroot/App_Data 
    build:
      args:
          - hostname=cms.sitefinity.local