version: '2.5'

services:
  sitefinitysql:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    container_name: sitefinitysql
    environment:
    - SA_PASSWORD=Sitefinity14@2022
    - ACCEPT_EULA=Y
    ports:
    - "5400:1433" 
    mem_limit: 2g
    

  sitefinitywebapp:
    image: ${DOCKER_REGISTRY-}sitefinitywebapp:14.1.7824
    container_name: sitefinitywebapp
    build:
        context: .
        dockerfile: SitefinityWebApp/Dockerfile
    dns: 8.8.8.8
    ports:
    - "8085:80" 
    mem_limit: 8g
    depends_on:
      - sitefinitysql
    
