version: '3.4'

services:
  sitefinitysql:
    hostname: sitefinitysql
    container_name: sitefinitysql
    environment:
      - SA_PASSWORD=Sitefinity14@2022
      - ACCEPT_EULA=Y      
      - MSSQL_PID=Express
    ports:
      - "5433:1433"
    volumes:
      - ./../data/sql_data:/var/opt/mssql/data
  sitefinitywebapp:
    hostname: sitefinitywebapp.local
    container_name: sitefinitywebapp
    ports:
      - "8085:80"
    volumes:
      - ./../data/app_data:C:/inetpub/wwwroot/App_Data 
  sitefinityrenderer:
    hostname: sitefinityrenderer.local
    container_name: sitefinityrenderer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
    ports:
      - "5000"
      - "5001"
    volumes:
      #- ${APPDATA}\microsoft\UserSecrets\:C:\Users\ContainerUser\AppData\Roaming\microsoft\UserSecrets
      - ${USERPROFILE}\.aspnet\https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https
      